# Avoid long parameter lists
ParameterLists:
  Max: 5
  CountKeywordArgs: true

MethodLength:
  CountComments: false
  Max: 15

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 4

# Limit line length
LineLength:
  Enabled: false

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

AmbiguousRegexpLiteral:
  Enabled: false

Eval:
  Enabled: false

# Configuration parameters: MaxSlashes.
RegexpLiteral:
  Enabled: false
